services:
  api:
    build:
      context: .
    volumes:
      - .:/src
      - ${DATA_FILES_ROOT}/:/data_files/
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    networks:
      - mynetwork
    container_name: apikaddo_api_1

  db:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ${DATA_FILES_ROOT}/:/data_files/
    networks:
      - mynetwork
    container_name: apikaddo_db_1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    container_name: apikaddo_redis_1

  celery:
    build:
      context: .
    command: celery -A api worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/src
    networks:
      - mynetwork
    container_name: apikaddo_celery_1
    
networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
